### ISSUE TITLE
"Enter" key not opening files

### ISSUE THREAD

**Issue by fedeantuna** [kyazdani42/nvim-tree.lua#1004]
**OS**
Fedora 35

**Neovim version**
NVIM v0.6.1

**Nvim-tree version**
Commit: 589e39d6423fb99882f5626d96d70300866d52ca

**Describe the bug**
When navigating on Nvim-tree, pressing Enter key (<CR>) or 'o' doesn't open the file. I also have this in my settings:

```
mappings = {
    custom_only = false,
    list = {
        { key = { "l", "<CR>", "o" }, cb = tree_cb "edit" },
        { key = "h", cb = tree_cb "close_node" },
        { key = "v", cb = tree_cb "vsplit" },
    },
},
```

Version 2e1f82d8c0c57cbc2bfdc041a3aff26947559a1e is working as expected. Is it possible that something changed and I have to write a different setting?

**To Reproduce**
Update Nvim-tree to 589e39d6423fb99882f5626d96d70300866d52ca

**Expected behavior**
Pressing Enter key (<CR>) or 'o' should open the file.

**Comment by CLTsolutions** [comment]
I came here because I am having the same issue. Glad to see it's already documented. `<CR>` was working fine for me. I used it to open my plugin config file, and when I saved, my plugins updated (I'm assuming nvim-tree also updated). After that `<CR>` stopped opening files. @fedeantuna, using `tab` seems to be a work around for me at the moment.

**Comment by gegoune** [comment]
Try changing it to:

```lua
{ key = { "l", "<CR>", "o" }, action =  "edit" },
```

**Comment by kyazdani42** [comment]
cb is deprecated now, the documentation is up to date :)
