### ISSUE TITLE
Restrict tree traversal to current working dir

### ISSUE THREAD

**Issue by steliyan** [kyazdani42/nvim-tree.lua#1037]
## Is your feature request related to a problem? Please describe.
Restrict the tree traversal to the current working dir.

## Additional context
My workflow consists of opening a project dir and staying there all the time. If I need to switch between projects, I use `tmux`, so I don't really want to be able to go outside my working dir.

## Describe the solution you'd like
Integrate the following code to the plugin itself. :))

_\* Of course, handle edge-cases as I haven't tested a lot of scenarios, although I didn't hit any problems with my monkey-patching approach._ 🙈 

## Describe alternatives you've considered
Initially, I've tried passing a callback to the `dir_up` action, but this doesn't work if you have the root folder shown as you can change it, not by `-`, but by pressing `Enter` on it.

```lua
local change_dir_action = require('nvim-tree.actions.change-dir')
local original_force_dirchange = change_dir_action.force_dirchange

local function force_dirchange(foldername, ...)
  if vim.fn.getcwd() > foldername then
    return
  end

  original_force_dirchange(foldername, ...)
end

change_dir_action.force_dirchange = force_dirchange
```

## Config
```lua
require('nvim-tree').setup({
  hijack_netrw = true,
  hijack_cursor = true,
  nvim_tree_respect_buf_cwd = false,
  update_cwd = false,
  actions = {
    open_file = {
      quit_on_open = true,
    },
    change_dir = {
      enable = false,
      global = false,
    },
  },
  update_focused_file = {
    enable = true,
    update_cwd = false,
    ignore_list = {},
  },
  git = {
    enable = true,
    ignore = false,
    timeout = 500,
  }
})
```

Maybe this is something that can go in the wiki, although it's a bit hacky.

**Comment by kyazdani42** [comment]
I agree it's a bit hacky and a bit too specific to be implemented in the plugin. I guess a simple wiki page would do the trick :)

**Comment by alex-courtis** [comment]
I hacked this into change-dir with a restrict option: #1171 https://github.com/kyazdani42/nvim-tree.lua/pull/1171/files

It works for the situations I tried: global, change_cwd, close/open.

What do you think about this as an option @kyazdani42 ?

**Comment by alex-courtis** [comment]
An alternative for you @steliyan : add a `.` [custom action](https://github.com/alex-courtis/arch/blob/master/config/nvim/lua/amc/nvim-tree.lua#L8).

**Comment by alex-courtis** [comment]
@steliyan I would be grateful if you could test the branch that attempts to resolve this: https://github.com/kyazdani42/nvim-tree.lua/pull/1171

**Comment by kyazdani42** [comment]
i think it wouldn't be too much but the naming seems a bit incorrect. Maybe something like `restrict_above` or something like that.

**Comment by alex-courtis** [comment]
> restrict_above

That works.

**Comment by kyazdani42** [comment]
closed in #1037

**Comment by benbrastmckie** [comment]
I'm a little late to the party, but wanted to ask what `restrict_above_cwd` does and how it works. I tried reading through the help docs, but couldn't sort it out. I believe that this may do what I want, i.e., makes nvim-tree set the top of the directory tree to the place where the file I'm opening is. Any pointers would be greatly appreciated.

**Comment by alex-courtis** [comment]
> I'm a little late to the party, but wanted to ask what `restrict_above_cwd` does and how it works. I tried reading through the help docs, but couldn't sort it out. I believe that this may do what I want, i.e., makes nvim-tree set the top of the directory tree to the place where the file I'm opening is. Any pointers would be greatly appreciated.

Find file will happen only if that file is within cwd.

In practice, that means that the tree won't change if the file is outside of it.

**Comment by gegoune** [comment]
Could documentation be improved?

**Comment by alex-courtis** [comment]
Yes. `actions.change_dir` and `update_focused_file` are very related but we don't link them together well.

**Comment by benbrastmckie** [comment]
Thanks for your help. After continuing to poke around through the documentation, I'm still having trouble. Here is the issue: 

If I open `nvim` from any directory without specifying a file, I would like to be able to navigate to/create a directory with `nvim-tree`, change to that directory with `<C-]>` so that only that directory and its contents are shown, and then save my session so that when I reopen that session I only have the files in the project directory displayed in `nvim-tree`. However, each time I return to the session, the original full directory is shown (e.g., the home folder if that is where I began when I opened `nvim`.) 

I am curious if there is a way for `<C-]>` to change the cwd so that it is not only displayed, but also saved when I create a new session. I tried changing around various settings but without reproducing the behaviour that I'm looking for. 

What does work is to run the `:cd /wherever/my/directory/lives` command and then save my session. What I want to know if there is a way to make this automatic with `<C-]>` in `nvim-tree`. Although the documentation is definitely systematic, it's hard for me to tell which options if any will produce the functionality that I'm looking for. Put otherwise, the descriptions of the options included in the documentation are a little terse. Anyhow, thanks again for your help and for a great plugin!

**Comment by alex-courtis** [comment]
> I am curious if there is a way for `<C-]>` to change the cwd so that it is not only displayed, but also saved when I create a new session. I tried changing around various settings but without reproducing the behaviour that I'm looking for.

This is a difficult problem; insufficient information is persisted across sessions.

We're working on it #1992

**Comment by benbrastmckie** [comment]
Is there any simple hack that I might use in the meantime? For instance, perhaps I could remap `<C-]>` to something that: first ran `:cd X` where the `X` is replaced with the directory under the cursor, and then second, reloaded `nvim-tree` so that the new cwd is at the top of the tree. When I save my session, it will save the directory that I `:cd` into.

**Comment by alex-courtis** [comment]
> Is there any simple hack that I might use in the meantime? For instance, perhaps I could remap `<C-]>` to something that: first ran `:cd X` where the `X` is replaced with the directory under the cursor, and then second, reloaded `nvim-tree` so that the new cwd is at the top of the tree. When I save my session, it will save the directory that I `:cd` into.

You could experiment with `prefer_startup_root` and `sync_root_with_cwd` for some control over tree root.

Additionally you can set `root_dirs` with some root directories that you prefer.

`update_focused_file.update_root` can also be useful to change root when the file is outside of the current.
