### ISSUE TITLE
A few feature suggestions

### ISSUE THREAD

**Issue by johnpyp** [kyazdani42/nvim-tree.lua#111]
Hi, I just started using this plugin and it's really awesome :)

I have a couple feature suggests, mostly minor things, that could make a for better UX:

#### 1. Add a function for moving up the directory without losing your focus.

Currently, the only way to expand the scope of the current tree root directory is by moving to the top, then `cd`ing into it. When you do this, the current directory focus is also lost.

It would be nice to have a "goto parent" function and corresponding binding so you could simply move up the directory tree but retain the focus.

#### 4. Inverting the binding format for far more flexible bindings and easier functionality implementation

This one is probably more ambitious implementation wise. The basic idea is just to invert the bindings to a map of keys -> functions, rather than functions to keys. Then, if you want to add complex functionality for a certain key that isn't supported in a contained function, you can chain them together, and add ternaries.

The only file explorer that I know of that does this is [coc-explorer](https://github.com/weirongxu/coc-explorer#custom-mappings-example), but it makes the bindings very powerful and easy to customize.

Using this functionality, I could implement the suggestions from above trivially just in the bindings settings, doing something like this:

```viml
" `u` for "up"
'u': ['vim:gg', 'cd', 'LuaTreeFindFile'],
'<CR>': ['edit', 'LuaTreeClose']
```

This is just a silly theoretical syntax, but shows some of the possibilities of what could be done. 

Additionally, this gives more flexibility by allowing you to just define a set of utility functions that aren't coupled to any specific binding, and the bindings can become simple compositions of those functions. For example, in `coc-explorer` the "edit" function isn't even defined, rather it's left up to the keybinds which can define it easily through a binding with a ternary: 
```
"<CR>": ["expandable?", ["expanded?", "collapse", "expand"], "open"]
```

---

Thanks for the consideration :)

If you want me to make separate issues for these I can do that as well.

**Comment by kyazdani42** [comment]
i don't have much time to spend on this plugin anymore, as it has all the functionnalities i need for myself, but i'll keep reviewing and accepting PRs :) !

**Comment by johnpyp** [comment]
I'm not too familiar with lua, but I'd love to learn and it doesn't seem too complex so I'd be happy to make some PRs for each of these over the next few days. Do all of these suggestions seem like something you'd be willing to merge in?

The last one is a bit different, since it's a breaking change and big paradigm shift, so I'll leave that one for later.

**Comment by kyazdani42** [comment]
the last one you could add bindings to your config. It's not that easy to interact with this tree because i didn't make the api very accessible, but you could manage to get stuff done (i don't really think viewing mapping is that useful to add, you could just type `:map` and you'll have all the bindings for your configs).
You could add `au BufNew * lua require'tree'.close()` to close the file on buffer creation (not sure that would be perfectly what you would expect).

Although i'd like to rewrite the setup so it can be done through lua without accessing the vim.g, which would make this plugin initialization way easier, i wonder if breaking the way people configured the tree is actually a good idea. 

Anyway most of the time i wouldn't refuse features that people need, specially if they spent time working on them.

**Comment by johnpyp** [comment]
Coming back to this plugin a few months later and I see now the keymapping config has inverted! Thanks a lot :)
