### ISSUE TITLE
`README.md` misaligned in the tree

### ISSUE THREAD

**Issue by zuoxinyu** [kyazdani42/nvim-tree.lua#1183]
### Description

The `README.md` doesn't has a circle dot between icon and name.
and, the `test.xml` seems has a wider icon than the others, maybe it's related about my terminal fonts.

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Operating system and version

WSL2 on Windows 10

### nvim-tree version

ce463a5

### Steps to reproduce

1. nvim
2. :NvimTreeOpen

### Expected behavior

the icons column should be aligned.

### Actual behavior

![image](https://user-images.githubusercontent.com/9346419/164592950-257acdaa-c398-41b6-93af-d3d70b500a2c.png)
![image](https://user-images.githubusercontent.com/9346419/164592983-f21e36fd-44f7-4fbd-a00d-81cf5c8b70eb.png)

### Minimal config

```Lua
use {
       'kyazdani42/nvim-tree.lua',
       requires = { 'kyazdani42/nvim-web-devicons' },
       config = function()
           vim.g.nvim_tree_icons = { default = '' }
           require 'nvim-tree'.setup {
               diagnostics = { enable = true },
               git = { ignore = false },
               filters = { dotfiles = true },
           }
       end,
   }
```

**Comment by alex-courtis** [comment]
That is mostly expected behaviour. For git, the cirular appearing icon indicates untracked files. README.md is either ignored or not dirty, hence no icon.

Icon spacing for that XML icon, the placement of git status icons etc. is currently suboptimal. There is a large piece of work underway to refactor the renderer which should resolve these sorts of issues. Please follow that in https://github.com/kyazdani42/nvim-tree.lua/issues/877

Closing this issue; please reopen if you have any further questions.
