### ISSUE TITLE
Do we need a 'stable' branch?

### ISSUE THREAD

**Issue by d0u9** [kyazdani42/nvim-tree.lua#1193]
**Is your feature request related to a problem? Please describe.**

Many times, I update nvim plugins and get failed on `nvim-tree`. Then, I spend much time on tracing what was going on and what is a valid commit to me.

The latest commit of master branch is not always working. For the time I post this issue, `c46653b4a3035cad7882004b3a1a49b771777a35` is broken that folder icons are not shown. I traverse back many commits to find a working one, it is full of pain.

**Describe the solution you'd like**
Add a `stable` branch in which commits are fully tested.

**Describe alternatives you've considered**

**Additional context**

**Comment by kyazdani42** [comment]
well sometimes i refactor much of the old code, which create some issues for a short while, but since people use the master branch, i can have fast feedback on those changes and fix them on the fly.
I'm not sure about maintaining a stable branch, @alex-courtis do you think it would be a good idea ?
We could potentially make a small "release cycle" for stable releases instead, but maintaining this seems a bit painful.
Maybe some tests would be better in order to avoid instabilities ?

**Comment by alex-courtis** [comment]
### 1: A New Stable Branch
This might be a problem:
* Most (all?) plugins use master, with no stable/release branch
* Many plugin managers such as vundle do not support branches
* Users may have configured the plugin to use master, more likely they just default to the git default branch at time of installation

The stable branch would thus need to be master.

### 2: Releases By Tag
Regularly tagging master with SEMVER release version is a practice used by most software.

As per the above stable branch, this is not used by vim plugins.

Some Plugin managers support installation of plugins by version tag, but have no means of updating when a new version is released.

### 3: Release Cycle To Stable master
* Create a development or unstable branch
* Merge PRs and fixes to development
* Merge emergency fixes to development as well as master 
* Merge development to master 

### 4: CI / Automated Tests
This is a good software engineering practice. A few plugins use this.

We would need to:
* Build testing infrastructure
* Write tests

This is desirable in the far long term however is not practical in the near future, due to the great size of the task.

### A quick audit of my plugins. Note that I explicitly set coc.nvim to release.
```
:; for d in *; do cd $d; echo $d; git branch; cd ..; done
base16-vim
* master
bufexplorer
* master
coc.nvim
  master
* release
editorconfig-vim
* master
gitsigns.nvim
* main
nvim-tree.lua
* master
nvim-web-devicons
* master
ReplaceWithRegister
* master
tagbar
* master
terminus
* main
vim-airline
* master
vim-airline-themes
* master
vim-commentary
* master
vim-fugitive
* master
Vim-Goto-Header
* master
vim-repeat
* master
```

**Comment by d0u9** [comment]
I prefer an `unstable` branch if `master` continuously integrates brand new features and fixes. Review the commits in the history of `master` branch, it contains chunks of commits in one single day or even a few hours. I think it was a series of "test-and-commit" cycles to a developer who got stuck by bugs. I think the hot test work is better done in one `unstable` branch which is never touched by users who always use `master` by default.

**Comment by aspeddro** [comment]
> Releases By Tag

It is possible to create fixed tags with the same name, an example is `rust_analyzer` which uses `nightly`.

https://github.com/rust-lang/rust-analyzer/releases/tag/nightly

**Comment by alex-courtis** [comment]
> It is possible to create fixed tags with the same name, an example is `rust_analyzer` which uses `nightly`.

That's a great solution.

Unfortunately it might be tricky moving people from master to stable. See https://github.com/kyazdani42/nvim-tree.lua/issues/1193#issuecomment-1107961593

We could be clever and change the default branch to unstable and change master to a tag.

**Comment by kyazdani42** [comment]
a `dev` branch as default, using master as stable, and tagging `nightly` tags on `dev` ? so people using master would use stable by default, and the dev branch would be a bit more stable :) Something like auto tagging a nightly every 2/3 days, and manually releasing to master once we are sure the plugin is stable enough ?

**Comment by aspeddro** [comment]
Some ideas:

First:

- keep `master` as default => `stable`
- `dev` as unstable and tagging `nightly` tags on dev every `x` days

Second:

- Continue merging PRs / fixes to `master`.
- Release `stable` tag every `x` days.

**Comment by kyazdani42** [comment]
First idea would be better for users, but more burden for us
Second idea would be better for us, but users would need to explicitly use the tag in their config.

**Comment by alex-courtis** [comment]
> Second idea would be better for us, but users would need to explicitly use the tag in their config.

I'm warming to the second. Most vim plugin are happy with unstable master. Anyone who wants stability can specifically configure it.

**Comment by kyazdani42** [comment]
Can close, see https://github.com/kyazdani42/nvim-tree.lua/releases/tag/nightly. We'll release once every week before merging feature and breaking change PRs :)

**Comment by still-dreaming-1** [comment]
I read this entire thread and am confused. I'm coming from the README where it shows: `tag = 'nightly' -- optional, updated every week. (see issue #1193)`. In most projects, the term "nightly" refers to an unstable build that is automatically generated once per day during off work hours, but are you saying nightly here is sort of the opposite of that, being the most stable way to be on something that will keep updating to newer versions over time?

**Comment by alex-courtis** [comment]
> I read this entire thread and am confused. I'm coming from the README where it shows: `tag = 'nightly' -- optional, updated every week. (see issue #1193)`. The term "nightly" is scary to people looking for stability. In most projects, the term "nightly" refers to an unstable build that is automatically generated once per day during off work hours, but are you saying nightly here is sort of the opposite of that, being the most stable way to be on something that will keep updating to newer versions over time?

Yes,  `nightly` is a bit misleading.

Stable branch is coming...
