### ISSUE TITLE
LuaTreeFindFile doesn't find file in non-working directory

### ISSUE THREAD

**Issue by LoydAndrew** [kyazdani42/nvim-tree.lua#141]
If you cd in nvim-tree  in any directory that doesn't contain current buffer and invoke  `LuaTreeFindFile` it will toggle nvim-tree but won't find file. 
Same behaviour if your current buffer is not in your working directory.

**Comment by kyazdani42** [comment]
maybe because i only search for files in the subtree, not outside the tree (imagine i'd have to search for files in the whole filesystem, wouldn't it be quite slow ?).
I might be able to do this search though, asynchronously it wouldn't be too hard to implement i guess. But it would need quite a bit of code, i don't really have time for that lately. It would be a good feature to add though.

**Comment by LoydAndrew** [comment]
Nerdtree plugin works this way. It really finds file even if you cd in a tree window or in a command line. Maybe it should be something like `getcwd()` and then find file in that directory and open it in that directory, just a guess.

**Comment by kyazdani42** [comment]
well if someone wants to implement this i'd be glad to accept a PR. I'll also add this in the rewrite, but it might take some time to finish.

**Comment by kyazdani42** [comment]
fixed in `1.1.4` (66f46b204f1624)
