### ISSUE TITLE
File deletion prompt is less intuitive than it used to be

### ISSUE THREAD

**Issue by hermitmaster** [kyazdani42/nvim-tree.lua#1441]
### Description

Not so much an issue as a preference, but ba5c18dc2b43599067d999933469098073e1941c introduced a change that changed the confirmation prompt to only accept `1` or `2` as options instead of `y` or `n`. A minor annoyance, but an annoyance nonetheless. 

Thanks for a great plugin!

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
```

### Operating system and version

macOS 12.4

### nvim-tree version

ba5c18dc2b43599067d999933469098073e1941c

### Minimal config

```lua
Any config that loads nvim-tree should do it.
```

### Steps to reproduce

Open nvim-tree and attempt to delete a file.

### Expected behavior

Prompt expects `y` or `n`

### Actual behavior

Prompt expects `1` or `2`

**Comment by numToStr** [comment]
I second this. And also, after deletion the selection UI does not disappear
![image](https://user-images.githubusercontent.com/24727447/179689942-db159b11-7cd6-4a91-b667-4f8ca333ce5a.png)

**Comment by nghialm269** [comment]
hi @kyazdani42, regarding commit https://github.com/kyazdani42/nvim-tree.lua/commit/8dc2144e878921111c75a942af6abed685e15c01 , I'm using https://github.com/stevearc/dressing.nvim as `vim.ui.input` implementation, when the filename is too long, it truncates the title and I couldn't see the choices (y/n/r).

I think using `vim.ui.select` is a better fit since in this case we're selecting an option rather than inputting something. If user doesn't happy with the UI/UX, they can override `vim.ui.select` instead.

**Comment by steliyan** [comment]
Agree with @nghialm269. Maybe you can open a new issue @nghialm269? :)

**Comment by kyazdani42** [comment]
please open a feature request, this vim.ui api is causing more trouble than it solves for us it seems :smile:

**Comment by nghialm269** [comment]
@steliyan @kyazdani42 I opened a feature request here https://github.com/kyazdani42/nvim-tree.lua/issues/1483.
