### ISSUE TITLE
auto_close and tab_open doesn't work

### ISSUE THREAD

**Issue by fitrh** [kyazdani42/nvim-tree.lua#158]
I put this line in my configuration
```viml
let g:lua_tree_auto_close = 1
let g:lua_tree_tab_open = 1
```
I think these option will close the tree if it's the last window and will remain open in new tab if it's open before, but it seems doesn't work for me, am i did it wrong ?

**Specification**
OS : Arch Linux, kernel 5.9.14-arch1-1
Neovim : 
```sh
NVIM v0.5.0-dev+944-g82100a6bd
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by kyazdani42** [comment]
hum yeah the implement for the tab stuff is quite buggy and new bugs appears while neovim is evolving :/ It should be stable in the next version (when i have some time because i dont have that much time lately).
auto close should work though, when closing a window and the tree is the only window left.

**Comment by fitrh** [comment]
I don't know why auto_close doesn't work, i put in on opt directory and only loaded it if i use nvim nightly, is thar maybe cause of the problem ?

**Comment by fitrh** [comment]
And yeah, it is cause the problem, after put it in `start` directory, the auto_close is work.

**Comment by fitrh** [comment]
Using `packadd!` solve the auto_close problem, previously i use only `packadd`.

**Comment by kyazdani42** [comment]
variable handling is not greatly done, i'll change this in the version so users are able to set variable before or after loading
