### ISSUE TITLE
Fullscreen tree

### ISSUE THREAD

**Issue by pianocomposer321** [kyazdani42/nvim-tree.lua#200]
I was sure there would already be an issue open about this, but I didn't see one, so...

Is there a way to edit directories with this plugin, similar to netrw or nerdtree when hijack netrw is set? If not, is this feature planned?

Thanks.

**Comment by kyazdani42** [comment]
hi, what do you mean by 'edit directories' ? by typing `r` you can already rename it if that's what you mean.

**Comment by pianocomposer321** [comment]
Nope, sorry I should have been more specific.

When this plugin is not installed and netrw is enabled (which it is by default in all recent versions of [neo]vim), you can do `nvim .`, for example, and it will open the directory full-screen in netrw. If vim is already open, you can do `:e .` to open netrw in the current split window. With nerdtree installed, you can do the same thing but it will open in nerdtree instead of neovim. But with nvim-tree installed, not only does it not open the directory in the current split in nvim-tree, but it also breaks netrw.

**Comment by pianocomposer321** [comment]
http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/ for more info

**Comment by kyazdani42** [comment]
I'm not sure but a PR for fixing these netrw issues has been made (see #195).

**Comment by kyazdani42** [comment]
think this is ok now

**Comment by qgadrian** [comment]
@kyazdani42 I believe this issue is more of opening the tree in the current window (and explained [here](https://github.com/kyazdani42/nvim-tree.lua/issues/200#issuecomment-778416552)) and not a new side window with the file explorer.

I see there are _hijack_current_window_ functions and tested this behavior myself with little success. I'm not familiar with the code but I believe the overall architecture does not work well with this behavior, am I right? Is this feasible and/or something you have planned?

**Comment by kyazdani42** [comment]
opening directories through `:e dir` or `:vsplit dir` should change the tree base dir to this dir
