### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ZenoArrow** [kyazdani42/nvim-tree.lua#208]
Was just curious what could be done to add Windows support. Does this depend on changes being implemented in some of the nvim-tree dependencies?

**Comment by kyazdani42** [comment]
Hi, windows support would need a full proper path handling (resolving paths with `\` instead of `/`), i don't think it would be too hard, but it could raise new issues.
There might be some libuv calls that might differ from unix based systems. I'm not too sure and cannot test it out, i don't possess any windows machine.
I would accept a PR, that i would test properly on linux to make sure nothing breaks, and i'd trust windows support to anybody who wishes to maintain it.
