### ISSUE TITLE
Break window size after opening nvim-tree

### ISSUE THREAD

**Issue by vpeopleonatank** [kyazdani42/nvim-tree.lua#219]
Before I open nvim-tree.lua
![image](https://user-images.githubusercontent.com/30976876/109411074-f3c79080-79d1-11eb-99b9-43a044cb78e8.png)
After toggling it
![image](https://user-images.githubusercontent.com/30976876/109411081-080b8d80-79d2-11eb-87a7-364d0d7bf3b4.png)
And when close nvim-tree, the window size doesn't restore previous size.
![image](https://user-images.githubusercontent.com/30976876/109411120-4e60ec80-79d2-11eb-81c1-739eab6ef31b.png)

Can you add some hook after closing nvim-tree, to set the window size as previous state?

**Comment by kyazdani42** [comment]
i guess that would be ideal. I'll add that when i have some time if somebody doesn't do it first :)

**Comment by vpeopleonatank** [comment]
I used coc-explorer, I didn't see it's impl, but I feel that it use `<C-W>=` after closing file tree.

**Comment by kyazdani42** [comment]
i don't know if this would be a good solution, because windows might not all be at the same size when opening the tree. Something like bufferizing the windows width before opening and resetting them when closing might be better.
But this might not work if windows are closed while the tree is open, maybe synchronizing the cache on winclosed would help. I'll try to impl something like that

**Comment by YuchengShiKolmostar** [comment]
@kyazdani42 I dont think it's fixed... The toggle still feels like applying `<C-w>=`

**Comment by nyngwang** [comment]
Exactly what I want to ask...

**Comment by alex-courtis** [comment]
This problem is resolved. I can't say exactly when it was fixed...

Please open a bug report if you have problems in the future.
