### ISSUE TITLE
Blank on Nvim NvimTreeToggle

### ISSUE THREAD

**Issue by saifulapm** [kyazdani42/nvim-tree.lua#280]
Hello, Suddenly when I toggle nvim tree, there is no files. When I refresh, all files showing. It was perfect before. I don't what happen. Any Idea ? 

<img width="1275" alt="Screenshot 2021-04-09 at 5 53 33 PM" src="https://user-images.githubusercontent.com/3833316/114176227-b0f7c180-995c-11eb-84a6-bbb21bae28f9.png">

Please check this image. When toggle 2 time, Files is back. I use lazy load feature of Packer. 

Any Idea ?

Thanks

**Comment by kabouzeid** [comment]
Same here when I open with `nvim +NvimTreeToggle`. Refreshing the tree does work, but it's annoying :/

**Comment by shadow-asd** [comment]
same

**Comment by saifulapm** [comment]
I think recently Nvim Tree added lsp diagnostic feature. After this update, Lazy loading not working. I solved this by remove lazy loading for Nvim Tree.

**Comment by liubang** [comment]
same

**Comment by kabouzeid** [comment]
How can I disable lazy loading?

**Comment by saifulapm** [comment]
Are you using Packer ?

**Comment by kabouzeid** [comment]
No, Plug. And I'm not lazy loading via plugin manager. I use nvim +NvimTreeToggle to execute the command immediately on start

**Comment by sindrets** [comment]
This happens because initialization is deferred, and so it is not always done after `VimEnter`.

@kabouzeid If you always want to open nvim-tree when launching nvim you should set

```vim
let g:nvim_tree_auto_open = 1 " will open the tree when the package is loaded.
```

If you only use that command sometimes, you should change it to: `nvim -c 'let g:nvim_tree_auto_open=1'`.

But I also think it would be a good idea to have some sort of callback when the plugin has finished loading. @kyazdani42 maybe we could add something like a `ready` event in the new event handler?

**Comment by kabouzeid** [comment]
Thanks, I must've overlooked that option :)

**Comment by kyazdani42** [comment]
@sindrets this is a good idea, i guess we could provide this so nvim-tree.toggle is always called when setup is finished. I removed the asynchronous initialization so it might be quite easy to do (but this is also the reason why the lazy loading is not working properly anymore).

**Comment by folke** [comment]
Adding the following inside the `config` function for **Packer** `use` seems to work:
```lua
require"nvim-tree".on_enter()
```

**Comment by kyazdani42** [comment]
refer to the `on_ready` event if you use lazy loading ! closing this :)

**Comment by akinsho** [comment]
@kyazdani42 how does one use the `on_ready` event for lazy loading. I read through the docs and tried to see where I'd implement it but I'm not sure how it should work? The `on_enter` command posted above works fine for me (note to anyone reading this you should add your config opts before you call that function), just wondering if there is a better more official way

**Comment by sindrets** [comment]
@akinsho I think something like this would work for lazy loading:

```lua
require'nvim-tree.events'.on_nvim_tree_ready(function ()
  vim.cmd("NvimTreeRefresh")
end)
```

**Comment by kyazdani42** [comment]
@akinsho you need to pass `opt = true` in order to lazy load the plugin in packer though.
but yes @sindrets is right

**Comment by akinsho** [comment]
Thanks both 👍🏿 guess there's a preference issue here as `on_enter` will block till the tree is loaded and `on_ready` is async but has an empty tree for a second or less (more of a random observation than anything else since both work).

PS: re. packer you don't actually need to specify `opt` if any of the keys you are using imply lazy loading e.g. `cmd`, `keys` and a few more all imply lazy loading so packer will make them opt without specifying

**Comment by kyazdani42** [comment]
good to know !

**Comment by languitar** [comment]
This still seems to exist. If I am fast after nvim startup with manually opening the tree, nothing is shown. As I don't want to always open the tree when entering vim: what is the accepted solution here to solve this?

**Comment by folke** [comment]
@languitar inside your config, add the following:

```lua
require("nvim-tree.events").on_nvim_tree_ready(function()
  vim.cmd("NvimTreeRefresh")
end)
```

**Comment by akinsho** [comment]
It might be worth mentioning in the README that based on how this plugin handles loading it's not really worth lazy loading anyway since it's quite inexpensive to load. If you use `PackerProfile` with it loaded on startup it doesn't even breach a 1ms to load so the actual faff of trying to lazy load it isn't really worth it

**Comment by folke** [comment]
@akinsho good point. I pretty much lazy load my whole config, but since working on my own plugins I basically came to the same conclusion. Most plugins don't do that much on startup apart from defining some commands. Not true for all plugins of course.

**Comment by languitar** [comment]
Actually I do not use lazy loading and I am still struggling with this issue.

**Comment by akinsho** [comment]
@languitar if you are lazy loading it to save on startup time I don't think it's worthwhile to do that. If you still want to do @.folke's snippet should work I used to use that but I don't think there's anyway to avoid the delay currently, which is why I stopped lazy loading it, but the snippet should mean that it does eventually populate after a 1-2secs or so.

Tbh if you are almost instantaneously trying to open the tree then it seems even less worthwhile to be lazy loading it since it's something you need at startup.

**Comment by languitar** [comment]
As said, I don't have lazy loading enabled for nvim-tree. So why do I still need that workaround?

**Comment by akinsho** [comment]
Sorry ignore me then I totally misread what you wrote 😓 I'll leave this to the maintainers then

**Comment by kyazdani42** [comment]
@languitar could you open a new issue please ? make sure before that your neovim version is recent enough, the plugin well updated and `set debug=throw` in your init.vim does not throw on startup or when running this command :)
