### ISSUE TITLE
nvim-tree does not show the git status of files on Windows.

### ISSUE THREAD

**Issue by AnthonyK213** [kyazdani42/nvim-tree.lua#347]
This issue appears after #335 on Windows but WSL. 
*current master*
![屏幕截图 2021-04-25 123608](https://user-images.githubusercontent.com/29994167/115981080-d246e780-a5c3-11eb-9035-3253f857af35.jpg)
*before #335*
![屏幕截图 2021-04-25 124222](https://user-images.githubusercontent.com/29994167/115981084-d7a43200-a5c3-11eb-8a27-db4320cae6d5.jpg)

**Comment by kyazdani42** [comment]
hi, I won't be available for the next two weeks, just rollback to that version until I can merge a fix

**Comment by AnthonyK213** [comment]
👌

**Comment by sindrets** [comment]
Oh, the problem is the single quotes in the shell command here:

https://github.com/kyazdani42/nvim-tree.lua/blob/f39869514645b98ec30bc8826763c288b6cbdbef/lua/nvim-tree/git.lua#L17

I just tested instead using `shellescape` and that works. Tested on a windows VM with windows native nvim. I'll put up a PR.

**Comment by AnthonyK213** [comment]
👍
