### ISSUE TITLE
Default buffer settings

### ISSUE THREAD

**Issue by JoshTRN** [kyazdani42/nvim-tree.lua#379]
Hello. I'm pretty new to lua and nvim, so pardon my ignorance, but is there a way to set the default buffer settings in the tree? I find myself having to always `:set ignorecase` and `:set relativenumber` .

I couldn't figure out how to do this reading the docs, so if you have any insight it would be much appreciated. Thanks

**Comment by kyazdani42** [comment]
not sure what you mean, ignorecase is global so it's up to your config to define it, and relativenumber is a window local option (which you could turn in the tree by setting `require'nvim-tree'.view.View.winopts.relativenumber = true`

**Comment by cloggier** [comment]
@kyazdani42 on unrelated note, I have just tried setting `require'nvim-tree'.view.View.winopts.cursorline = true` but getting an error: `Error in packer_compiled: Vim(lua):E5108: Error executing lua [string ":lua"]:52: [string "..."]:0: attempt to index field 'view' (a nil value)`, do you think it might be because `cursorline` does not exist in that table in the first place? If so, would you accept PR adding it?

**Comment by kyazdani42** [comment]
sorry i spelled it wrong:
`require'nvim-tree.view'.View.winopts.relativenumber = true`

**Comment by cloggier** [comment]
It works, thank you very much!

**Comment by gbaranski** [comment]
do I have to set both
```
vim.o.relativenumber = true
```
and
```
require'nvim-tree.view'.View.winopts.relativenumber = true
```
or maybe there is some way to do both of them at once?

**Comment by kyazdani42** [comment]
`vim.o` sets global vim values, the tree has other default values so you have to set them both if you want to change the tree options.
