### ISSUE TITLE
Hangs on saving

### ISSUE THREAD

**Issue by dvogt23** [kyazdani42/nvim-tree.lua#389]
After install nvim-tree nvim hangs on saving 🤔  somtime just 2sec, sometime more ...
![nvim-tree](https://user-images.githubusercontent.com/9352647/118956573-0366cd80-b960-11eb-8b47-d9da4f03e17a.gif)

any idea? whats info need for debug?

**Comment by kyazdani42** [comment]
i'm really not sure what this is about. Are you sure this comes from nvim-tree ? Your tree is not even opened so this seems strange to me

**Comment by dvogt23** [comment]
Yes, just after the include with the packer this happens 😞 so unfortunately yes ... after dropping this plugin, everything looks fine. Can I help with some additional info?

**Comment by kyazdani42** [comment]
hm, maybe a minimal init so i can reproduce ? and your neovim version :)

**Comment by dvogt23** [comment]
sure thing :) nvim `NVIM v0.5.0-dev+nightly-105-g66f9dd3c6`
```lua

tree_cb = require'nvim-tree.config'.nvim_tree_callback
vim.g.nvim_tree_bindings = {
  ["<CR>"]           = tree_cb("edit"),
  ["<C-CR>"]          = tree_cb("cd"),
  ["<C-v>"]          = tree_cb("vsplit"),
  ["<C-x>"]          = tree_cb("split"),
  ["<C-t>"]          = tree_cb("tabnew"),
  ["<BS>"]           = tree_cb("close_node"),
  ["<S-CR>"]         = tree_cb("close_node"),
  ["<Tab>"]          = tree_cb("preview"),
  ["I"]              = tree_cb("toggle_ignored"),
  ["H"]              = tree_cb("toggle_dotfiles"),
  ["R"]              = tree_cb("refresh"),
  ["a"]              = tree_cb("create"),
  ["d"]              = tree_cb("remove"),
  ["r"]              = tree_cb("rename"),
  ["<C-r>"]          = tree_cb("full_rename"),
  ["x"]              = tree_cb("cut"),
  ["c"]              = tree_cb("copy"),
  ["p"]              = tree_cb("paste"),
  ["-"]              = tree_cb("dir_up"),
  ["q"]              = tree_cb("close"),
}

vim.g.nvim_tree_side = 'left'
vim.g.nvim_tree_width = 30
vim.g.nvim_tree_ignore = {
  '.git', 'node_modules', 'dist', '.cache'
}
vim.g.nvim_tree_auto_open = 0
vim.g.nvim_tree_auto_close = 0
vim.g.nvim_tree_follow = 1
vim.g.nvim_tree_indent_markers = 1
vim.g.nvim_tree_hide_dotfiles = 1
vim.g.nvim_tree_git_hl = 1
vim.g.nvim_tree_root_folder_modifier = ':~'
vim.g.nvim_tree_tab_open = 0
vim.g.nvim_tree_show_icons = {git = 0, folders = 1, files = 0}

vim.g.nvim_tree_icons = {
  symlink = '',

  git = {
    unstaged = "✗",
    staged = "✓",
    unmerged = "",
    renamed = "➜",
    untracked = "★"
  },

  -- folder = {default = "", open = " "}
  folder = {
   default = "",
   open = "",
   empty = "",
   empty_open = "",
   symlink = "",
   symlink_open = "",
  },
}
```

**Comment by kyazdani42** [comment]
i cannot reproduce the lag :/ seems weird that this is nvim-tree related, could you disable the ligne 15 in `tree.vim` and tell me if the lag is still here ? If not, this cannot be nvim tree related.

**Comment by Shatur95** [comment]
Same here, happens when git integration is enabled. Try to disable it.

**Comment by dvogt23** [comment]
> Same here, happens when git integration is enabled. Try to disable it (`vim.g.nvim_tree_git_hl = 0`).

thanks! Thats it ... thanks @kyazdani42 for investigation and this great plugin 🥇 🙏🏾

**Comment by kyazdani42** [comment]
git integration could indeed slow down the plugin as it's using cli commands (and i'm not sure how fast cli commands happen but they are usually slower than libraries). If something like https://github.com/libgit2/luagit2 can be integrated at some point that would be nicer i suppose

**Comment by Samyak2** [comment]
I have the same issue with everything updated to the latest versions. Saving a file pauses everything for 1-2s. Opening neovim is slow too (~1.5s), but it's not captured by `--startuptime`. Removing `nvim-tree` fixes the slowdowns.

Also worth mentioning that this happens when opening neovim inside a large repository (even without opening a file). Opening neovim in my home dir or my config dir does not show the same behaviour.

> `vim.g.nvim_tree_git_hl = 0`

This did not work for me, it was already disabled. Is there any other setup parameter that makes use of CLI commands?

I'll try making a minimal reproducible config. I'm on `NVIM v0.5.0-dev+1357-g192f89ea1`

**Comment by Shatur95** [comment]
> This did not work for me, it was already disabled. Is there any other setup parameter that makes use of CLI commands?

There is also `nvim_tree_show_icons`.

**Comment by Samyak2** [comment]
That fixed the delay on save. Thank you!

Although the lag on startup still exists.

**Comment by kyazdani42** [comment]
lag on startup i cannot reproduce, but it might be related to you shell. if you `set shell=/some/shell/without/config`, does the lag still exists ?

**Comment by Samyak2** [comment]
I tried setting shell to `/usr/bin/bash --noprofile --norc`, it did not change the startup time in any way. Takes nearly ~10s inside a large repo.

Should I open a new issue for this?

**Comment by kyazdani42** [comment]
set the shell through nvim maybe ? I'm really not sure how this plugin could affect 10seconds of startup time, this has been discussed many times and it was never this fault. Been using this for a long time, when i started writing it and never experienced this.
Maybe checkout the perf branch (check in the pull requests) and do some debugging because i'm not sure how a simple lua startup could take so much time. Do you have a low performance computer ?

**Comment by Samyak2** [comment]
> set the shell through nvim maybe ?

Yes, I that was the first thing I tried. I set `vim.o.shell` in my config and confirmed it inside nvim with `set shell?`

> Maybe checkout the perf branch (check in the pull requests)

I will try that.

> and do some debugging

I've never debugged/profiled lua in nvim before. I'll look it up, but if you know any specific references it would be helpful.

> Do you have a low performance computer ?

My laptop has 4 cores with HT (8 threads) (specifically i5-8265U), 16GB RAM and SSDs (no HDDs). I don't think it's a hardware performance issue.

---

Thank you for writing this plugin :heart:, I will try my best to debug this issue.

**Comment by Samyak2** [comment]
Aha! I found the issue. There were many, many untracked files - `395,986` of them! (I blame node_modules). Showing all of them even using the git command directly (`git status --porcelain=v1 --ignored=matching -u`) takes >7s.

Is there a reason `nvim-tree` needs to get the list of all untracked files and then loop through all of them? Looks like it's just to check for `gitignore`d files. Is there a configuration parameter to disable this? If not, would this be a useful addition? (I would like to contribute if so).

**Comment by kyazdani42** [comment]
hi @Samyak2, you debugged perfectly, thanks a lot :)
well indeed 400K files to track with git is slow. you could `vim.g.nvim_tree_gitignore = 0` in your init.lua to avoid ignoring files from gitignore but i'm not sure this is the issue here.
I need to get the whole list of the git statuses to apply git informations in the tree, of course if you have 400K changes it will slow down considerably.
Maybe just try to ignore these files ?

**Comment by Samyak2** [comment]
Yes, ignoring or deleting these files is a good solution.

But, I was wondering if it's possible to disable all git operations in `nvim-tree`.

I have the following set in my config:
```lua
vim.g.nvim_tree_git_hl = 0
vim.g.nvim_tree_gitignore = 0
vim.g.nvim_tree_show_icons = {
    git = 0,
    folders = 1,
    files = 1,
 }
```
and no git information shows up in the tree. So, is that git information really needed? I can send a PR to fix this if it's not needed.

**Comment by kyazdani42** [comment]
i think this has to do with `nvim_tree_gitignore` ? did you disable the feature ?

**Comment by kyazdani42** [comment]
i don't think so, if you can send a PR to fix it it'll be very welcome :)

**Comment by ChrisTsou** [comment]
i Stumbled in this today, you should definitely set git hl and git icons off by default.

**Comment by kyazdani42** [comment]
I'm not sure because I'm pretty sure most people use this. what i should do though is rewrite the git module because I can make it fast.

**Comment by splitDEV** [comment]
Hi, thank you for your time and effort for writing and maintaining this great plugin :smile: 

I have basically the same issue (hanging on startup/buffer save/opening fugitive for >3s) when editing my dotfiles and figured out it relates to git as well:
I use a [bare git repository](https://www.atlassian.com/git/tutorials/dotfiles) for storing my dotfiles and I guess that you try to find the git root directory and end up in $HOME which has of course many untracked files (intentionally). I configured my dotfiles git in $HOME to status.showUntrackedFiles=false but I guess you try to find all untracked files in $HOME anyway?

Just a use case to take into account if you happen to rewrite the git module? :upside_down_face:
Because right now nvim-tree.lua is more or less unusable for me :disappointed:

**Comment by kyazdani42** [comment]
#549 
i'm working on a refactoring of git to make this more configurable
