### ISSUE TITLE
Cannot navigate previous folder after commit  714dee57e535c7d58b4455c4d8abdf7403f22275

### ISSUE THREAD

**Issue by ronisbr** [kyazdani42/nvim-tree.lua#439]
Hi!

After commit `3196205131a2d4d53d92d195215ee72343349e5b` I am having problems in macOS. First, I cannot go back to previous directories and the files are not opened in the correct directories. When I revert back, everything works fine. I am using the latest Neovim version (`master`).

**Comment by ronisbr** [comment]
Sorry, the problem occurred in commit `714dee57e535c7d58b4455c4d8abdf7403f22275`. I will change the title.

**Comment by ronisbr** [comment]
When I go to previous directory, nvim-tree shows this with the latest commit:

<img width="239" alt="Captura de Tela 2021-06-08 às 11 06 41" src="https://user-images.githubusercontent.com/1068295/121199862-a74de580-c849-11eb-8d01-a1a10e538991.png">

**Comment by cwebster2** [comment]
I think my issue is linked to this, and also on commit 714dee.  The issue i see is when i open files in a folder that isn't the root of the git tree.  I think this is an interaction with other things that force my `cwd` to the root of the git tree.  Here is a visual of what i see.

From `.vim/` i run `nvim lua/plugins.lua`
![image](https://user-images.githubusercontent.com/5762261/121215495-afa42180-c845-11eb-8cf2-b074cc56e4b1.png)

But if i `cd lua` then `nvim plugins.lua` i see this
![image](https://user-images.githubusercontent.com/5762261/121215635-cea2b380-c845-11eb-8e6a-8468c17d6bb6.png)

This is new behavior since updating nvim-tree.  This occurs in every git work tree on my system.  i have to open files from the git root (the directory returned by `git rev-parse --show-toplevel` or they do not open correctly.

**Comment by famiu** [comment]
For me if I do `~/.config/nvim/lua/plugins.lua` it opens nvim-tree instead of opening the file for some reason, could it be related to this?

**Comment by kyazdani42** [comment]
hi everyone, sorry for the inconvenience, if fixed both issues in 906a35cd0e7520e.
Could you tell me if it works for you ? I used to change dir on win change because of the dir changed event but this is now fixed and the '..' is fixed by using vim.fn.fnamemodify to get the proper path from the state.
@famiu not sure this is related to this but i haven't seen this issue at all

**Comment by famiu** [comment]
> hi everyone, sorry for the inconvenience, if fixed both issues in [906a35c](https://github.com/kyazdani42/nvim-tree.lua/commit/906a35cd0e7520eaff369688cb0a090240d7c2b9).
> Could you tell me if it works for you ? I used to change dir on win change because of the dir changed event but this is now fixed and the '..' is fixed by using vim.fn.fnamemodify to get the proper path from the state.
> @famiu not sure this is related to this but i haven't seen this issue at all

@kyazdani42 I don't know if it's related or not but the latest commit doesn't fix it for me

**Comment by kyazdani42** [comment]
this issue is unrelated to your issue then, please open a new one :)

**Comment by ronisbr** [comment]
Hi @kyazdani42 

Awesome! It is working perfectly now. Thank you very much for this quick fix!
