### ISSUE TITLE
Default keymaps cannot be unset

### ISSUE THREAD

**Issue by stevelacy** [kyazdani42/nvim-tree.lua#448]
I have `<Tab>` mapped to `C+w`, allowing me to tab to navigate right from any buffer including the tree: `nnoremap <Tab> <c-w>w`

With this default:
```lua
options = {
  ["<Tab>"]          = tree_cb("preview"),
}
```
`<Tab>` will always be consumed, removing it does not unset the value. Also setting it to an empty string of `""` still prevents the command from passing down. 
The only way I was able to allow `<Tab>` to navigate buffers was to remove this line entirely: https://github.com/kyazdani42/nvim-tree.lua/blob/d6ab59fd5acb7c71b1a10ace5a522a720460ad6e/lua/nvim-tree/view.lua#L56

I would like to be able to set the default maps to an empty list, then only add the ones I want. 
`let nvim_tree_disable_keybindings=1` disables them entirely, would it be possible to add an option for just an empty {} set of mappings?

Cheers

**Comment by sindrets** [comment]
To solve this problem you have to set all the key bindings yourself, which is a bit of a hassle, but not too bad. You can take a look at [how I currently do it](https://github.com/sindrets/dotfiles/blob/cafb333578a1ad482531ba5091c5171b32525d24/.config/nvim/lua/nvim-config/plugins/nvim-tree.lua#L67-L120). It can of course be done simpler than this as well.

@kyazdani42 Can we not just make it so that `nvim_tree_disable_keybindings` only disables the defaults, and still lets users define their own through `nvim_tree_bindings`? That would be a lot more convenient in my opinion. It would practically not even be a breaking change seeing as if people have `nvim_tree_disable_keybindings` enabled, they probably don't have anything defined in `nvim_tree_bindings`.

**Comment by kyazdani42** [comment]
i wouldn't be against it, also adding a mode to the mapping keeping it 'n' by default. I'm very busy lately but i'd be happy to implement that when i have some time.

**Comment by kyazdani42** [comment]
implemented many changes for keymaps. You can now disable default keymaps by setting `vim.g.nvim_tree_disable_default_keybindings = 1`. You can also specify a mode. Refer to the documentation for more informations.

**Comment by sirex** [comment]
I found how to override `<Tab>`:

```lua
local nvim_tree = require'nvim-tree'

local function go_to_prev_window()
  vim.cmd("wincmd p")
end

nvim_tree.setup {
  view = {
    mappings = {
      custom_only = false,
      list = {
        { key = "<Tab>", action = "preview", action_cb = go_to_prev_window },
      },
    },
  },
}
```

But, I could not find, how to override `preview`, it looks, that I can't directly associate `key` with `action_cb`, I must also provide `action`. But at least I was able to override `<Tab>`.

**Comment by kyazdani42** [comment]
yep, this mapping style is not great anyway, it was made to avoid breaking changes :)

**Comment by evanrittenhouse** [comment]
Are we able to unbind `s` from `system_open`? I use `s` to trigger lightspeed in the nvim-tree pane, but after updating it doesn't work @kyazdani42

**Comment by alex-courtis** [comment]
Set the s action to "" : https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L675
