### ISSUE TITLE
Error when trying to move through the files using arrow or hjkl

### ISSUE THREAD

**Issue by hrqmonteiro** [kyazdani42/nvim-tree.lua#461]
When i open NvimTree and try to move up and down the files, i get this error:

![test3](https://user-images.githubusercontent.com/17055027/122688205-4632f400-d1f1-11eb-9e5b-279cb721499e.png)

And for some reason, it shows all the folders and files duplicated:

![test4](https://user-images.githubusercontent.com/17055027/122688242-85f9db80-d1f1-11eb-8147-b8191a8f42d9.png)

**Comment by gegoune** [comment]
Commit introducing first issue is 6dca42d09db1aa2511c3d2901313083143ea0829.

Disabling the feature with
```lua
vim.g.nvim_tree_hijack_cursor = 0
```
solves the issue.

Second issue seems to be introduced by ed23e1df1c654657a38003a2cb010003d6fc4dc9, in which @sindrets implemented reusable buffer.

That makes 1f1b25de last revision without both issues you mentioned.

**Comment by sindrets** [comment]
@gegoune Duplicate nodes was not introduced by ed23e1df1c654657a38003a2cb010003d6fc4dc9. This usually occurs when people misconfigure NvimTree. I.e. by calling `on_enter()` manually. Which causes the top level of the tree to be repopulated without removing the nodes that are already there. See for instance #342.

Duplicate nodes are not a problem in the current master with the default configuration (at least I can't reproduce it). I assume the reason you don't see duplicate nodes before that commit is that previously the tree was essentially reinitialized on every toggle.

Besides, all the code I wrote in that commit has been completely refactored and doesn't exist anymore.

**Comment by kyazdani42** [comment]
i should definitely do an issue template so we can narrow down the problems related to user configurations more easily.

**Comment by gegoune** [comment]
@sindrets Please do accept my sincere apologies, I did not mean to accuse your or your code. That commit was what `git bisect` told me and I did no more investigating before posting here. 

Surprisingly though I did not have `on_enter` in my config, so perhaps something else was causing it. I did not really (except for small change which I will describe below) change my configuration and, as you said, I am not seeing that problem on latest master. Didn't for a little while as matter of fact.

Hope you won't mind if I ask here @kyazdani42 , I was configuring nvim-tree with packer's `config` function for a long time until switching to `after/plugin/nvim-tree.lua` recently. That exposed an issue (nvim-tree is installed in `start/` package group): `vim.g.nvim_tree_auto_close = 1` would not be taken into account. I skimmed through code very quickly and noticed  (maybe mistakingly) that this variable is expected to exist before nvim-tree is loaded, which  in turn explains why it would be ignored. I then moved all `vim.g.nvim_tree*` variables to `plugin/nvim-tree.lua` which gets loaded before packages. All works as expected, but I ended up with configuration for your plugin in two places, for example `vim.g.nvim_tree_bindings` has to be in `after/plugin/` because it uses callbacks that are required from package that has to be loaded first.

So I guess my question is: is above all correct or am I mistaken there somehow. Also, how much simpler it would be to have `setup()` function (wink wink). :)

@sindrets, once again, apologies and big thanks for all your contributions.

**Comment by sindrets** [comment]
@gegoune No worries! No offense taken:) I realized it was a result of a git bisect, and I just wanted to clarify.

> Also, how much simpler it would be to have setup() function (wink wink). :)

I *really* want a lua setup function as well, as I think it's a lot cleaner. It would reduce a lot of redundant naming of options as well. I might put up a draft pr soon.

**Comment by kyazdani42** [comment]
i really want a setup function too but haven't got the time to work on that, it would resolve so many issues starting with the hard to read readme/documentation and user startup configurations.
Although this issue is not really closed (duplicate entries are basically caused with nvim sessions i believe #342)
