### ISSUE TITLE
:NvimTreeToggle command disappears after :PackerCompile|Sync

### ISSUE THREAD

**Issue by zeitchef** [kyazdani42/nvim-tree.lua#471]
Every time I run either `:PackerCompile` or `:PackerSync`, the `:NvimToggleTree` command no longer works and doesn't even appear as a cmdline option anymore (though `:NvimTreeOpen|Close` are still there).

How can I help debug this?

Edit: After closing nvim and reopening, the command works again.

**Comment by gegoune** [comment]
If it's not a typo then problem might be with vim packages, and how they are not reloaded, when packer reloads. Are you using packer's lazy loading functionality for nvim-free?

**Comment by zeitchef** [comment]
@kyazdani42 Yes, sorry that was a typo - indeed the command is `NvimTreeToggle`.
@gegoune Actually, I do lazy-load plugins by default.

**Comment by gegoune** [comment]
This is an issue with vim packages and/or Packer then. @wbthomason is aware of it.

**Comment by kyazdani42** [comment]
should i close this then ? Or this is related to how nvim tree does it's setup ?

**Comment by gegoune** [comment]
Unrelated. I had that issue with neogit. Don't think you can do anything on nvim-tree side to alleviate it.

**Comment by kyazdani42** [comment]
is there an issue in packer you could link to ?

**Comment by gegoune** [comment]
I don't think so. Had a discussion with @wbthomason about it on gitter.

**Comment by wbthomason** [comment]
The quick summary of what causes this:
- When we regenerate `packer`'s lazy-loaders, a new "fake" `NvimTreeToggle` command is generated if a user is lazy-loading `nvim-tree` on this command
- When compilation finishes, `packer` sources the new compiled file
- If `nvim-tree` was already loaded at the time of compilation, then the "real" `NvimTreeToggle` command gets overwritten
- Usually, when the fake command gets run, it deletes itself, `packadd`s the relevant plugin, and then runs the new command with the same name that the plugin provides
- However, if the plugin was already loaded, then running `packadd` again **does not** source its runtime files again, and so the real `NvimTreeToggle` doesn't get created again, and we get this error.

This is largely a trait (wouldn't say flaw, exactly) of native packages inherited by `packer` because it builds on native packages. The way we'd fix this would probably be to add logic to the lazy-loader to not create a fake command if a command with the same name exists - the downside of this approach being that, if you change the set of plugins loaded on a given command, that change will no longer be picked up until a restart. However, this latter case is probably relatively uncommon, so maybe this is worth doing.

**Comment by kyazdani42** [comment]
if i changed the setup to put every command configuration in the lua function, i might be able to override the packer's override ? I currently have most setup for commands/autocmd in vimscript which might cause issues with lazy loading

**Comment by ttbug** [comment]
The latest update has this problem again。
`Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:82: Vim:E492: Not an editor command: NvimTreeToggle`
