### ISSUE TITLE
absolute path and relative path

### ISSUE THREAD

**Issue by smartding** [kyazdani42/nvim-tree.lua#482]
When I open a file with nvim-tree.lua, and I run "echo expand('%)" or "ctrl-g", I always get the absolute path, which can be really long for some of the projects I work on.

But if I open a file with ":e path/to/file", or if I open with another plugin such as telescope.nvim, "echo expand('%)" or "ctrl-g" show the relative path, relative to the current working directory.

Is there any way I can configure nvim-tree.lua, so that "echo expand('%)" or "ctrl-g" will show the relative path?

**Comment by kyazdani42** [comment]
not yet, you could propose a PR to introduce such a change, i don't have a strong opinion on this

**Comment by eric-hansen** [comment]
I did end up fixing this locally, because I have an autocommand that assumes `expand("%")` will return the relative path.  I can submit a PR for this over the weekend.  

I'd like to make this configurable but not quite sure the proper way to approach that.  So if you have any guidance on that @kyazdani42 lemme know.
