### ISSUE TITLE
Bookmark a folder

### ISSUE THREAD

**Issue by Trid-collab** [kyazdani42/nvim-tree.lua#509]
Is it possible to bookmark folders so that we could jump back and forth ? Could you help me with it .

**Comment by kyazdani42** [comment]
hello, sorry for the delays. 
I think you could implement that on your end i believe, i'm not too sure i want to add that in the plugin right now because the codebase is getting a little messy and i'd like to fix bugs and do some refactorings before adding new features that would affect the existing codebase. I wouldn't be against this feature though.
You could maybe just write a lua function that gets the directory cwd on a node ? something like

```lua
local lib = require'nvim-tree.lib'
local function add_mark() 
  local node = lib.get_node_at_cursor()
  local bookmarks = {}
  bookmarks[node.absolute_path] = node.absolute_path
end

local function remove_mark()
  local node = lib.get_node_at_cursor()
  bookmarks[node.absolute_path] = nil
end

local function jump_to_dir(dirname)
  lib.change_dir(dirname)
end
```
or something like that

**Comment by r7vme** [comment]
@kyazdani42 thanks for your plugin. After migrating from nerdtree to nvim-tree, this is definitely really desired feature. I work on projects that have hundreds of nested in many levels subprojects (monorepo), so I was relying on bookmarks in nerdtree.

**Comment by kyazdani42** [comment]
I'll try to finish #612 that will be a first step towards implementing this i think. When i have some time.
If someone wants to give it a shot, go for it :)
