### ISSUE TITLE
[Question] I wonder why does not support windows technically

### ISSUE THREAD

**Issue by zgpio** [kyazdani42/nvim-tree.lua#59]

**Comment by kyazdani42** [comment]
please elaborate.

**Comment by zgpio** [comment]
Sorry for not explaining in detail. Need additional dependencies to support windows? Or, there is no plan to support windows. In theory, can a file browser plug-in supported by all platforms be realized through neovim+lua+libuv?

**Comment by kyazdani42** [comment]
well i don't plan to support windows because i don't use it, as most developers. There would be too much overhead. And i don't have the knowledge for it.
How do you handle the root of your filesystems ? What does windows returns when asking for a handle to a folder ? We should also change every `/` character to `\` which would be a pain and bad performance wise imo.
People using windows could use wsl and it would work just fine :)
I guess if somebody wants to implement the code for windows, i wouldn't mind, but it shouldn't affect performance ! :)
So if you know how to develop code related to windows fs, go for it, i would accept a PR :)

**Comment by zgpio** [comment]
I understand. Close for now.
