### ISSUE TITLE
Telescope exit closes vim

### ISSUE THREAD

**Issue by nagy135** [kyazdani42/nvim-tree.lua#609]
Hello I m just curios if this is intended behavior or if this is something that could be fixed.
There is this option
```viml
let g:nvim_tree_auto_close = 0 "0 by default, closes the tree when it's the last window
```
And I like that it closes vim when i kill last buffer in regular use. Issue is that when you open folder `nvim dir` and then open **Telescope** buffer and exit it, it also closes nvim itself. Is there a way for a initial tree to remain? I think first one should be outside of this behavior

Minor issue of mine but it happens regularly to me, so I just asked ...feel free to close

**Comment by kyazdani42** [comment]
The auto_close auto closes nvim when the tree is the last window so unfortunately there is no workaround for that i'm  afraid.
I'm not using this option since a long time because it conflicts too much with many behaviors, so i'm not sure how to fix the behavior because it already behaves as expected
