### ISSUE TITLE
[Feature Request] Show icons to the right

### ISSUE THREAD

**Issue by kishikaisei** [kyazdani42/nvim-tree.lua#616]
I would like to have the option to put the git status icons and such to the right, for me it would look cleaner as I am not fond of the unaligned file/folder names.

Current behaviour:
![actual](https://user-images.githubusercontent.com/1894123/132873938-fccbb8ef-3e40-4fbb-810f-6bff98f8ac6c.png)
Desired behaviour:
![desired](https://user-images.githubusercontent.com/1894123/132873984-b16c4adb-6c4b-4e65-9501-8bdbb19b7b9b.png)

**Comment by kyazdani42** [comment]
i think this is a duplicate of https://github.com/kyazdani42/nvim-tree.lua/issues/72 and https://github.com/kyazdani42/nvim-tree.lua/issues/553, not feasible at the moment, i'd have to rework the renderer because it's quite messy and would be hard to extend as it is without adding more spaghetti code in it :smile:

**Comment by kishikaisei** [comment]
Yeah I get it, it is kind of a duplicate I guess...
