### ISSUE TITLE
`autocmd FileType NvimTree` randomly not firing

### ISSUE THREAD

**Issue by goolord** [kyazdani42/nvim-tree.lua#636]
highlighting `NvimTreeNormal` in an autocmd for example seems to have a 50% change of actually doing anything

**Comment by goolord** [comment]
results change each `PackerCompile`

**Comment by kyazdani42** [comment]
would you mind sharing more informations ? for the au it should be `au FileType NvimTree` but i do not set the file type each time the view is displayed because i try to always keep the buffer active, that's why it might not be firing as expected. I might change a little bit the implementation in the view code to remove this behavior because its been quite a pain i must confess.
Not sure what you mean by results change each packercompile ?

**Comment by goolord** [comment]
i'll get a recording of it later, it's honestly very bizarre behavior and i don't know how to explain it. the only other information i have is that it started happening once https://github.com/kyazdani42/nvim-tree.lua/pull/603 was merged

**Comment by kyazdani42** [comment]
should work fine now, nvim tree buffer is created and destroyed appropriately
