### ISSUE TITLE
.gitignore regression

### ISSUE THREAD

**Issue by johnnovak** [kyazdani42/nvim-tree.lua#727]
The gitignore issue I reported was fixed a while ago, but now it's back again. Please refer to my original issue on how to test:
https://github.com/kyazdani42/nvim-tree.lua/issues/412

There's some weird new behaviour too, btw. If you keep re-saving the same file, the backup file (ending with `~`) will _sometimes_ disappear after the 3rd save...

**Comment by johnnovak** [comment]
> can you try #682 and tell me if this fixes your issue ? you'll need to install `tami5/sqlite.lua` in order to test it out. The PR is working but there are still improvements i need to make first. It fixes a lot of small issues with refresh and other things too.

Thanks, I'll try that in the next few days.

**Comment by johnnovak** [comment]
Tried it, with sqlite it's buggy in a different way :) With the sqlite branch filenames with no spaces seem to work work fine, so that's an improvement. But if the name contains at least one space and you re-save it in vim, then the backup shows up in the tree every time. Plus on every save the whole three flickers a bit, which is not too nice, but that's a different issue.

I'm not overly enthusiastic about making sqlite a requirement for this plugin. I prefer vim plugins with zero external dependencies. But perhaps you would only need it if you want enhanced git integration? I guess in that case it wouldn't be so bad.

So if sqlite is the way forward, I won't try to narrow the issue down on the main version, I'll wait until this hits main and give it some testing.

**Comment by kyazdani42** [comment]
I'm still not sure to merge this branch, i've tried to fix the flicker issue but due to running a job asynchronously, i have to redraw the tree multiple times which is not nice. Adding sqlite was supposed to fix issues on huge git repositories (at least not crashing nvim because of memory overflow), but it seems to add more overhead than issues it solves.
I might just simplify the git process to make it synchronous again, i think people that have git integration issues will just need to disable it.
Seems like git returns quoted paths when filenames have spaces, that's why the ignore implementation does not work. Will fix when i have some time :)

**Comment by johnnovak** [comment]
> I might just simplify the git process to make it synchronous again, i think people that have git integration issues will just need to disable it.

Probably that's the best. You can't have everything :)
