### ISSUE TITLE
:NvimTreeFindFile not working

### ISSUE THREAD

**Issue by AgentCosmic** [kyazdani42/nvim-tree.lua#783]
nvim-tree only opens the window but does not go to the file when I run `:NvimTreeFindFile`. I remember it working before. But it stopped working quite some time ago.

**Comment by waseidel** [comment]
I have just installed and that command isn't working

**Comment by kyazdani42** [comment]
works just fine for me, i cannot reproduce if you don't provide more informations.

**Comment by kuznetsss** [comment]
I updated today and it doesn't find file in tree in some cases. What information would be helpful to find out what's wrong?
I use nvim-tree with default options.

**Comment by xeluxee** [comment]
I'm experiencing the same problem
I think this issue is related to some LSP servers running in single file mode (e.g. clangd on a single file)
When I disable LSP (`:LspStop`) `NvimTreeFindFile` works correctly.
Maybe that happens because NvimTree tries to find LSP root directory, but since LSP is running in single file mode it goes to home directory

**Comment by xeluxee** [comment]
So this shouldn't be LSP-related, but it's a matter of reloading
If you press `R` after finding file NvimTree displays files well

**Comment by Dornat** [comment]
> If you press `R` after finding file NvimTree displays files well

I can confirm this. When I use `NvimTreeFindFile` it doesn't work properly. Then I press `R` and it works like a charm.

**Comment by kyazdani42** [comment]
still cannot reproduce even with provided steps...
Maybe someone could provide a minimal sample config file to reproduce this issue consistently.

**Comment by kuznetsss** [comment]
`NvimTreeFindFile` still doesn't work correctly for me after the fix

**Comment by AgentCosmic** [comment]
Fix didn't work for me either. Even after pressing `R`.

**Comment by xeluxee** [comment]
Just out of curiosity, are you LunarVim users?

**Comment by AgentCosmic** [comment]
Nope, custom config https://github.com/AgentCosmic/neovim

**Comment by kuznetsss** [comment]
I also use custom config https://github.com/kuznetsss/nvim_lua_config

**Comment by kuznetsss** [comment]
I have debugged the issue a little and find that here
https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/view.lua#L227
`pcall` returns error `Cursor position outside buffer`

Also if you put here
https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/lib.lua#L221
just `M.redraw()` instead of calling `git.load_project_status()` everything works fine for me.

So maybe to reproduce the issue you just need to be not in git repo
