### ISSUE TITLE
nvim-tree closes when a dirty buffer is saved.

### ISSUE THREAD

**Issue by nyinyithann** [kyazdani42/nvim-tree.lua#894]
**OS**
macOS Catalina
version 10.15.7

**Neovim version**
0.6.1

**Nvim-tree version**
master branch, tag 1.6.7

**Describe the bug**
When a dirty buffer is saved, Nvimtree closes.

**To Reproduce**
1. open nvimtree
2. open a buffer and enter something
3. save the buffer

**Expected behavior**
Nvim should stay open when buffers are saved.

https://user-images.githubusercontent.com/156037/149091131-eb035872-8a7e-4cb7-9691-2ae4d192732b.mov

**Comment by guilhermerodz** [comment]
I believe this issue is responsible for even more bugs.

I'm facing an issue where:
1. You have installed a plugin that uses floating windows (`telescope.nvim` or `which-key.nvim`)
2. You run `nvim <directory>` into your project folder. Your buffer then is expected to be a `NvimTree` buffer.
3. Now, try to open & close any `telescope.nvim`'s pickers, `which-key` panel or any other plugin that uses floating window.
4. When you close that floating window, the entire `Neovim` process will exit.

**Comment by guilhermerodz** [comment]
It turns out, this issue is related to the `auto_close` functionality.

NvimTree doesn't seem to be tracking open & dirty files correctly. It listens to Nvim's `WinClosed` autocmd, but something is wrong afterwards.

While this issue isn't fixed, you still can avoid suddenly losing your work by disabling `auto_close` at `nvim_tree.setup{}`  (set it to `false`).

**Comment by kyazdani42** [comment]
i think i might just remove this feature at some point because it causes too many weird behaviors.

**Comment by kyazdani42** [comment]
should be working now, closing this. Can you confirm ?
